N = int(input())
Numbers = list(map(int, input().split()))
all_positive = all(x>0 for x in Numbers)
any_palindromic = any(str(x)==str(x)[::-1] for x in Numbers)
print(all_positive and any_palindromic)
